### ISSUE TITLE
Soul Edge\Soul Blade Missing Records Text

### ISSUE THREAD

**Issue by LodanZark** [duckstation-unoff-issue-tracker-admin/duckstation-unofficial-issue-tracker#77]
Mednafen:
![Soul Blade (USA) (Rev 1)-221202-030217](https://user-images.githubusercontent.com/11250310/209685330-54b77218-1f3f-4208-9695-5e2b6451a366.png)
Duckstation:
![SLUS-00240_2022-12-02_02-56-36](https://user-images.githubusercontent.com/11250310/209685332-135f255a-f915-4e9d-8ed5-ac0a769d8279.png)

**Comment by sigarettenstank** [comment]
@LodanZark Thanks for the report but I've already got this one on the list.

https://github.com/duckstation-unoff-issue-tracker-admin/duckstation-unofficial-issue-tracker/issues/14

**Comment by LodanZark** [comment]
@sigarettenstank Before I post the report, I did search the issues about soul edge, and I forgot to do the same about soul blade, It seems this issue affects all game versions\revisions. I will close the report as it is duplicated.
